### ISSUE TITLE
metal boundry condition non-obvious

### ISSUE THREAD

**Issue by JonathanFraser** [bendudson/freegs#13]
I am trying to relax a CT equilibrium in a metal flux conserver, by applying psival=0 constraints along the wall surface in addition to a series of coils along the same surface. Simply applying the constraint results in numerous spurious x and o points in additions to the desired values.  Moreover, there is significant equilibria outside the boundary. 

![circle_meta](https://user-images.githubusercontent.com/27691/47887180-417c6000-ddfb-11e8-8837-19f14c7c27ee.png)

What is the expected procedure to apply appropriate constraints?

**Comment by bendudson** [comment]
Interesting test case! I think you have used the correct constraints. Does increasing the number of points constrained, and/or the number of  coils improve the result?

The spurious O-points and X-points may be a failure of the critical point finding code, or it may be finding the O- and X-points in between the coils. I'm a bit confused about the equilibrium outside the wall.

Would it be possible to send me the code used to generate this ( benjamin.dudson at york.ac.uk )?

**Comment by bendudson** [comment]
I've added some things to FreeGS, to allow the psi at the plasma boundary to be specified rather than calculated from the X-point locations. The code is in a branch "metal-wall":
https://github.com/bendudson/freegs/blob/metal-wall/09-metal-wall.py
Attached is the result with 200 coils & constraints.

![metal-wall](https://user-images.githubusercontent.com/219233/47921089-a3949e00-deab-11e8-85a9-43c510698d6e.png)

**Comment by JonathanFraser** [comment]
so [this](https://gist.github.com/JonathanFraser/f1062d9b82b71bb1c3f659ad3de9aef2) is the code I'm trying to run. I don't see any thing that different from your solution but I'll give yours a try.

**Comment by JonathanFraser** [comment]
ok, so it looks like a Rmin of 1mm is too small. Given that the domain was only 20cm I figured that would be ok. I know that Rmin of zero will result in singularities, but what defines the minimum value?

**Comment by JonathanFraser** [comment]
I'm satisfied with the answer here.

**Comment by bendudson** [comment]
Hi @JonathanFraser Would you like to be involved in an APS abstract about FreeGS, for a mini-conference organised by PlasmaPy “Growing an open source software ecosystem for plasma science”? If so please email me, benjamin.dudson at york dot ac dot uk.
