### ISSUE TITLE
isoflux and xpoint values should be same?

### ISSUE THREAD

**Issue by jwscook** [bendudson/freegs#26]
I imagine that this doesn't really matter given the point of the test, but referring to https://github.com/bendudson/freegs/blob/b3b4c06af0b5257f999e600452f8c5c0d2be6337/freegs/test_readwrite.py#L22-L23

should the R-Z points be the same in both isoflux and xpoints?

**Comment by bendudson** [comment]
Not necessarily: These settings will make an unbalanced lower double null, where the two X-points are not connected together. Probably a comment could be added here to explain the settings used.

**Comment by jwscook** [comment]
Ok, I just thought I'd check
