### ISSUE TITLE
Issue with 05-fixed-boundary.py

### ISSUE THREAD

**Issue by jmorris-uk** [bendudson/freegs#33]
Hi @bendudson

I'm trying to run some of the example files and example 5 doesn't seem to work on my machine (WSL Ubuntu 18.04 LTS). See screenshot below.

![image](https://user-images.githubusercontent.com/46964268/89638286-760c2e00-d8a3-11ea-8d50-a1bd2b557a93.png)

Cheers

**Comment by bendudson** [comment]
Thanks! Yes, I get the same problem on my machine. I'll look into it.

**Comment by bendudson** [comment]
I think this is fixed in PR #34 but see if it works for you. Have a good weekend!
