### ISSUE TITLE
Problem reading gfile from fiesta

### ISSUE THREAD

**Issue by kripnerl** [bendudson/freegs#6]
```python
import matplotlib.pyplot as plt
from freegs import _geqdsk
gfile = "..."
with open(gfile, 'r') as f:
   ...:     eq = _geqdsk.read(f)
plt.figure()
plt.contour(eq['psi'])
plt.show()
```
Link to gfile: [gfile](https://github.com/kripnerl/pleque/blob/develop/test/test_files/compu/baseline_eqdsk)

The gfile is generated by Fiesta code and is not exactly according to standards (by the way it is using Fortran matrix order); however, you can find it useful to implemented into your code.

**Comment by ZedThree** [comment]
Looks like [our regexp][1] is missing an optional '+' at the beginning. I'm just checking that this doesn't break existing files.


[1]: https://github.com/bendudson/freegs/blob/master/freegs/_fileutils.py#L77
