### ISSUE TITLE
Question: Minor radius definition

### ISSUE THREAD

**Issue by pabloprf** [bendudson/freegs#61]
In `equilibrium.py`, the minor radius `minorRadius()` is defined as the average distance from `Rgeo` to the separatrix points. Then that is used in the calculation of the effective elongation and aspect ratio. 
What's the motivation of this definition of the minor radius? As far as I know, we typically refer the minor radius as the half-width of the midplane intercept (i.e. `(R_max-R_min)/2`). The effective elongation, as defined e.g. in Doyle NF 2007 (https://iopscience.iop.org/article/10.1088/0029-5515/47/6/S02), uses this definition.
I believe that the definition given right now in `equilibrium.py` is more of an "effective minor radius", where higher elongation plasmas will result is a higher value of this quantity.

**Comment by chrismarsden7** [comment]
@pabloprf Hi Pablo, I originally wrote this method. At the time I was hesitant as to ensure that the (R_max-R_min)/2) definition wasn't some sort of large aspect ratio approximation. If it isn't then I agree it should be updated.

**Comment by bendudson** [comment]
There have been many changes in the latest version of FreeGS at https://github.com/freegs-plasma/freegs (Thanks Chris!). Please raise any future issues in that repository, thanks!
