### ISSUE TITLE
ffprime and pprime 

### ISSUE THREAD

**Issue by kripnerl** [bendudson/freegs#9]
Why do you store these values as `workk` since they are equal to `ffprime` and `pprime` (there may be a different sign of these). 

I can push correction if there is no other intent in this code. 

https://github.com/bendudson/freegs/blob/7b0cd21be116956c3dcb4f9979f08c676e735470/freegs/_geqdsk.py#L199-L200

**Comment by bendudson** [comment]
I think in the files I was reading these quantities were wrong or set to zero, and I didn't know what they were supposed to be. Very happy if you could push a change to `ffprime` and `pprime`. Thanks!
